name: Inspiration from life
link: //blog.chengbo.net
pygments: true
permalink: /:year/:month/:day/:title.html
timezone: Etc./UTC
paginate: 10
paginate_path: page//:num
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
